### PR TITLE
Support for tasks

### LINKED ISSUE #4: Create yarn app for running tasks
Yarn app for running streams is based on container groups because containers are expected to stay up until stream is undeployed and groups will restart failed containers. This model doesn't work with tasks which are expected to be one-off execution of a container(s). Task deployer should then submit task via this app which then runs task via module launcher.

### LINKED ISSUE #6: YARN SPI: Add support to launch external JVM for tasks
As a user, I'd want to launch an external JVM for _tasks_ when using `YARN` SPI.

### PR DESCRIPTION
**Pull request by jvalkeal**
- New yarn app which is able to run tasks.
- Rename existing stream classes and projects to be
  clear with tasks.
- Internal fixes to support two yarn app types in a same
  deployer.
- Use SHDP 2.3.0.RC2 and state machine 1.0.2.RC1
- Fixes #4
- Fixes #6

Build distribution:
$ mvn clean package -DskipTests

Wipe existing dirs and make sure you can write to root or you have existing `/dataflow` directory.
$ hdfs dfs -rm -r /dataflow
$ hdfs dfs -rm -r /tmp/hdfs-sink

Extract to tmp location
$ unzip spring-cloud-dataflow-admin-yarn-dist/target/spring-cloud-dataflow-admin-yarn-dist-1.0.0.BUILD-SNAPSHOT.zip

Modify redis/hadoop settins using spring-cloud-dataflow-admin-yarn-1.0.0.BUILD-SNAPSHOT/config/servers.yml

Start admin, shell and/or cli:

$ ./spring-cloud-dataflow-admin-yarn-1.0.0.BUILD-SNAPSHOT/bin/dataflow-admin-yarn
$ ./spring-cloud-dataflow-admin-yarn-1.0.0.BUILD-SNAPSHOT/bin/dataflow-shell
$ ./spring-cloud-dataflow-admin-yarn-1.0.0.BUILD-SNAPSHOT/bin/dataflow-yarn-cli shell

dataflow:>stream create --name s1 --definition "time|log" --deploy 
dataflow:>stream create --name s2 --definition "time|hdfs --rollover=200" --deploy 

dataflow:>task create --name t1 --definition "timestamp"
dataflow:>task launch --name t1
dataflow:>task launch --name t1
dataflow:>task launch --name t1

### CODE REVIEW

**Comment by trisberg** [comment]
Getting compile error:

```
[INFO] Compiling 10 source files to /Users/trisberg/Projects/spring-cloud-dataflow-admin-yarn/spring-cloud-dataflow-admin-yarn/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/trisberg/Projects/spring-cloud-dataflow-admin-yarn/spring-cloud-dataflow-admin-yarn/src/main/java/org/springframework/cloud/dataflow/module/deployer/yarn/YarnModuleInstanceStatus.java:[24,62] cannot find symbol
  symbol:   class State
  location: class org.springframework.cloud.dataflow.module.ModuleStatus
[ERROR] /Users/trisberg/Projects/spring-cloud-dataflow-admin-yarn/spring-cloud-dataflow-admin-yarn/src/main/java/org/springframework/cloud/dataflow/module/deployer/yarn/YarnModuleInstanceStatus.java:[36,35] cannot find symbol
  symbol:   class State
  location: class org.springframework.cloud.dataflow.module.ModuleStatus
[ERROR] /Users/trisberg/Projects/spring-cloud-dataflow-admin-yarn/spring-cloud-dataflow-admin-yarn/src/main/java/org/springframework/cloud/dataflow/module/deployer/yarn/YarnModuleInstanceStatus.java:[54,16] cannot find symbol
  symbol:   class State
  location: class org.springframework.cloud.dataflow.module.deployer.yarn.YarnModuleInstanceStatus
[ERROR] /Users/trisberg/Projects/spring-cloud-dataflow-admin-yarn/spring-cloud-dataflow-admin-yarn/src/main/java/org/springframework/cloud/dataflow/module/deployer/yarn/YarnModuleInstanceStatus.java:[24,62] cannot find symbol
  symbol:   class State
  location: class org.springframework.cloud.dataflow.module.ModuleStatus
[ERROR] /Users/trisberg/Projects/spring-cloud-dataflow-admin-yarn/spring-cloud-dataflow-admin-yarn/src/main/java/org/springframework/cloud/dataflow/module/deployer/yarn/YarnModuleInstanceStatus.java:[36,35] cannot find symbol
  symbol:   class State
  location: class org.springframework.cloud.dataflow.module.ModuleStatus
[ERROR] /Users/trisberg/Projects/spring-cloud-dataflow-admin-yarn/spring-cloud-dataflow-admin-yarn/src/main/java/org/springframework/cloud/dataflow/module/deployer/yarn/YarnModuleInstanceStatus.java:[54,16] cannot find symbol
  symbol:   class State
  location: class org.springframework.cloud.dataflow.module.deployer.yarn.YarnModuleInstanceStatus
[ERROR] /Users/trisberg/Projects/spring-cloud-dataflow-admin-yarn/spring-cloud-dataflow-admin-yarn/src/main/java/org/springframework/cloud/dataflow/module/deployer/yarn/YarnModuleInstanceStatus.java:[42,53] cannot find symbol
  symbol:   variable State
  location: class org.springframework.cloud.dataflow.module.ModuleStatus
[ERROR] /Users/trisberg/Projects/spring-cloud-dataflow-admin-yarn/spring-cloud-dataflow-admin-yarn/src/main/java/org/springframework/cloud/dataflow/module/deployer/yarn/YarnModuleInstanceStatus.java:[42,83] cannot find symbol
  symbol:   variable State
  location: class org.springframework.cloud.dataflow.module.ModuleStatus
[INFO] 8 errors 
```

**Comment by trisberg** [comment]
Probably related to https://github.com/spring-cloud/spring-cloud-dataflow/commit/3fb02d0a4367a5b2e92bc56d54ca5b66bd258959

**Comment by trisberg** [comment]
got the task to run. The logging messages have a %PARSER_ERROR[wEx] prefix - any ideas where that comes from?

```
%PARSER_ERROR[wEx]2015-12-07 19:27:30.203  INFO 2815 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] launched with the following parameters: [{}]
%PARSER_ERROR[wEx]2015-12-07 19:27:30.220  INFO 2815 --- [           main] o.s.batch.core.job.SimpleStepHandler     : Executing step: [step1]
%PARSER_ERROR[wEx]2015-12-07 19:27:30.227  INFO 2815 --- [           main] tampTask$$EnhancerBySpringCGLIB$$cdaab38 : 2015-12-07 19:27:30.227
%PARSER_ERROR[wEx]2015-12-07 19:27:30.241  INFO 2815 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] completed with the following parameters: [{}] and the following status: [COMPLETED]
```

**Comment by trisberg** [comment]
Also, where is the source for the TimestampTask?

**Comment by jvalkeal** [comment]
Old timestamp task in our repos for which there's no source code. Logging is broken inside that task so don't care about it.

**Comment by trisberg** [comment]
Hmm, seems like we should fix that first, so we can test properly. Or, am I missing something?

**Comment by trisberg** [comment]
There is a PR here - https://github.com/spring-cloud/spring-cloud-task-modules/pull/1

**Comment by trisberg** [comment]
Downloaded the `timestamp-task` and logging looks good when running locally:

```
2015-12-07 16:46:38.971  INFO 622 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] launched with the following parameters: [{}]
2015-12-07 16:46:38.983  INFO 622 --- [           main] o.s.batch.core.job.SimpleStepHandler     : Executing step: [step1]
2015-12-07 16:46:38.990  INFO 622 --- [           main] ampTask$$EnhancerBySpringCGLIB$$ccc1e4d7 : 2015-12-07 16:46:38.990
2015-12-07 16:46:38.996  INFO 622 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] completed with the following parameters: [{}] and the following status: [COMPLETED]
```

**Comment by trisberg** [comment]
Passing in arguments that contain a space isn't working right, get's truncated at the space. I created a stream like this:

```
dataflow:>task create --name t2 --definition "timestamp --format='yyyy-MM-dd HH:mm:ss.SSS Z'"
```

and see this in the logs:

```
%PARSER_ERROR[wEx]2015-12-07 21:59:46.087  INFO 6305 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] launched with the following parameters: [{-format=yyyy-MM-dd}]
%PARSER_ERROR[wEx]2015-12-07 21:59:46.109  INFO 6305 --- [           main] o.s.batch.core.job.SimpleStepHandler     : Executing step: [step1]
%PARSER_ERROR[wEx]2015-12-07 21:59:46.115  INFO 6305 --- [           main] ampTask$$EnhancerBySpringCGLIB$$26e3a699 : 2015-12-07
%PARSER_ERROR[wEx]2015-12-07 21:59:46.144  INFO 6305 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] completed with the following parameters: [{-format=yyyy-MM-dd}] and the following status: [COMPLETED]
```

**Comment by jvalkeal** [comment]
Spaces should work now within the definition.

**Comment by trisberg** [comment]
The logging issue is present in the local SPI as well, so it's a more general issue

**Comment by trisberg** [comment]
Closed via commit c715235a9901ea807fca3236bae2fa121afebc07

**Pull request closed without merging**
