### PR TITLE
Use banner text from dataflow-server-core

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Remove existing banner and include banner.txt from POM
 - Update to use dataflow-server snapshot
 - Update name to use in MANIFEST

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
This depends on https://github.com/spring-cloud/spring-cloud-dataflow/pull/1033

**Comment by jvalkeal** [comment]
This need to wait as RC1, afaik, will go with SCDF 1.1.0.RC1.

**Comment by jvalkeal** [comment]
Btw, why would we do this. Now banner will have text `Data Flow Server for Apache Yarn 1.1.0.BUILD-SNAPSHOT` (or whatever version is build). Yarn and SCDF core may have different versions. I makes much more sense to use server impl version rather than SCDF core version.

**Comment by jvalkeal** [comment]
Ah, right, now I looked that other PR.

**Comment by jvalkeal** [comment]
Squashed and fixed merge per https://github.com/spring-cloud/spring-cloud-dataflow-server-yarn/commit/896e37a11906d061823571d29a76832ac13dedca

**Pull request closed without merging**
